### ISSUE TITLE
Testing the new conversion version

### ISSUE THREAD

**Issue by zdavatz** [sapstern/edifactconverter#1]
Thank you for the new update.

Now if I try to convert from EDIFACT D 96A to XML I get this:
```
~/.software/edifactconverter> java -cp openedifact-converter/target/openedifact-converter-2.2-SNAPSHOT.jar:openedifact-xsd-libs-01B/target/openedifact-xsd-libs-01B-1.1-SNAPSHOT.jar com.sapstern.openedifact.run.ConverterRunner -process flat -fileIn /tmp/edifact_d_96a_convert_to_xml -ns ns0
org.xml.sax.SAXException: Parsing of UNH failed, no D_0065 found, possible problem with namespaceprefix, check XML
	at com.sapstern.openedifact.sax.EdifactSaxParserToFlat.parse(EdifactSaxParserToFlat.java:213)
	at com.sapstern.openedifact.run.ConverterRunner.main(ConverterRunner.java:34)
```

**Comment by zdavatz** [comment]
This is the file that I am trying to convert to XML: 
[edifact_d_96a_convert_to_xml.txt](https://github.com/sapstern/-edifactconverter-/files/4652204/edifact_d_96a_convert_to_xml.txt)

**Comment by sapstern** [comment]
get rid of the -ns ns0

**Comment by zdavatz** [comment]
then I get the following:

```
java -cp openedifact-converter/target/openedifact-converter-2.2-SNAPSHOT.jar:openedifact-xsd-libs-01B/target/openedifact-xsd-libs-01B-1.1-SNAPSHOT.jar com.sapstern.openedifact.run.ConverterRunner -process flat -fileIn /tmp/edifact_d_96a_convert_to_xml

org.xml.sax.SAXException: Parsing of UNH failed, no D_0065 found, possible problem with namespaceprefix, check XML
	at com.sapstern.openedifact.sax.EdifactSaxParserToFlat.parse(EdifactSaxParserToFlat.java:213)
	at com.sapstern.openedifact.run.ConverterRunner.main(ConverterRunner.java:34)
```
